[versions]
# Core Minecraft dependencies
paper = "1.21.11-R0.1-SNAPSHOT"

# External "hooks" or plugins that we might interact with
mechanicsCore = "4.2.0-SNAPSHOT"
mythicMobs = "5.9.0"
weaponMechanics = "4.2.0-SNAPSHOT"

# Shaded dependencies
bstats = "3.1.0"
commandApi = "11.1.0"
foliaScheduler = "0.7.5"


[libraries]
# Core Minecraft dependencies
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

# External "hooks" or plugins that we might interact with
mechanicsCore   = { module = "com.cjcrafter:mechanicscore", version.ref = "mechanicsCore" }
mythicMobs      = { module = "io.lumine:Mythic-Dist", version.ref = "mythicMobs" }
weaponMechanics = { module = "com.cjcrafter:weaponmechanics", version.ref = "weaponMechanics" }

# Shaded dependencies
bstats                   = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
commandApi               = { module = "dev.jorel:commandapi-paper-core", version.ref = "commandApi" }
commandApiKotlin         = { module = "dev.jorel:commandapi-kotlin-paper", version.ref = "commandApi" }
foliaScheduler           = { module = "com.cjcrafter:foliascheduler", version.ref = "foliaScheduler" }
