blank_issues_enabled: true
contact_links:
  - name: CubeDev Discord
    url: https://discord.gg/ERVgpfg
    about: If you are having trouble with config, come and ask us in the weaponmechanics-support channel